name: Lint

on:
  push:
  pull_request:
    branches: [master]

permissions:
  contents: read

jobs:
  lint:
    runs-on: ubuntu-latest
    name: php-cs
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up php
        uses: shivammathur/setup-php@v2
        with:
          php-version: "8.0"
          coverage: none
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Lint
        uses: docker://oskarstark/php-cs-fixer-ga
        with:
          args: --diff --dry-run